spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busfleetdb
    username: root
    password: mydatabase
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

server:
  port: 8081